language: go
go:
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync
  - go get -u github.com/mgechev/revive

before_script:
  - revive -formatter friendly $(go list ./... | grep -v /vendor/)

script:
  - sh ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)